spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/recipes
    password: postgres
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    '[org.springframework.security]': debug
